apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulltrace.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pulltrace.labels" . | nindent 4 }}
data:
  logLevel: {{ .Values.config.logLevel | quote }}
  watchNamespaces: {{ .Values.config.watchNamespaces | quote }}
  historyTTL: {{ .Values.config.historyTTL | quote }}
  reportInterval: {{ .Values.config.reportInterval | quote }}
