apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pulltrace.fullname" . }}-pod-reader
  labels:
    {{- include "pulltrace.server.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pulltrace.fullname" . }}-pod-reader
  labels:
    {{- include "pulltrace.server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pulltrace.fullname" . }}-pod-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "pulltrace.server.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
