{{- if and .Values.agent.auth.token (not .Values.agent.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulltrace.fullname" . }}-agent-token
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pulltrace.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.agent.auth.token | quote }}
{{- end }}
