apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pulltrace.agent.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pulltrace.agent.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pulltrace.server.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pulltrace.server.labels" . | nindent 4 }}
