{{- include "pulltrace.validateServiceType" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulltrace.fullname" . }}-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pulltrace.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.server.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "pulltrace.server.selectorLabels" . | nindent 4 }}
